### ISSUE TITLE
For windows platform i get json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by N0l2n** [Ekultek/WhatBreach#14]
Hello, please add type for windows platform. 
I get json.decoder.JSONDecodeError

**Comment by N0l2n** [comment]
This is full report:

`Traceback (most recent call last):
  File "whatbreach.py", line 5, in <module>
    main()
  File "C:\Users\me\.whatbreach_home\whatbreach\main.py", line 45, in main
    api_tokens = grab_api_tokens()
  File "C:\Users\me\.whatbreach_home\lib\settings.py", line 248, in grab_api_tokens
    tokens[token_identifier] = json.load(data)
  File "C:\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Klairm** [comment]
same here

**Comment by Stef16Robbe** [comment]
wsl aswell, windows is not the issue

**Comment by Ekultek** [comment]
is there a certain token you arent adding?
