### ISSUE TITLE
Traceback Error - raw_input not defined

### ISSUE THREAD

**Issue by therealOri** [Ekultek/WhatBreach#22]
Idk how to fix this issue.

```bash
Traceback (most recent call last):
  File "/home/ori/OSINT/WhatBreach/whatbreach.py", line 5, in <module>
    main()
  File "/home/ori/OSINT/WhatBreach/whatbreach/main.py", line 45, in main
    api_tokens = grab_api_tokens()
  File "/home/ori/OSINT/WhatBreach/lib/settings.py", line 241, in grab_api_tokens
    item = lib.formatter.prompt(
  File "/home/ori/OSINT/WhatBreach/lib/formatter.py", line 20, in prompt
    question = raw_input(
NameError: name 'raw_input' is not defined
```
Any help would be appreciated. I also have all of the modules that would be needed installed already.

**Comment by therealOri** [comment]
I am using python3 and not python2.. `raw_input` has been replaced with just `input`.

ALSO weleakinfo has been seized by the gov so you ain't getting an api key from there anymore.
