### ISSUE TITLE
Linux: ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

### ISSUE THREAD

**Issue by yohlimem** [Ekultek/WhatBreach#28]
when i run the command: `python3 whatbreach.py -h` on linux i get this error messege
```
Traceback (most recent call last):
  File "/home/yahli/Documents/WhatBreach/whatbreach.py", line 1, in <module>
    from whatbreach.main import main
  File "/home/yahli/Documents/WhatBreach/whatbreach/main.py", line 5, in <module>
    from lib.cmd import Parser
  File "/home/yahli/Documents/WhatBreach/lib/cmd.py", line 3, in <module>
    import lib.settings
  File "/home/yahli/Documents/WhatBreach/lib/settings.py", line 11, in <module>
    from hookers.pastebin_hook import PastebinRawHook
  File "/home/yahli/Documents/WhatBreach/hookers/pastebin_hook.py", line 3, in <module>
    import requests
  File "/home/yahli/anaconda3/envs/WhatBreach/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/yahli/anaconda3/envs/WhatBreach/lib/python3.12/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/home/yahli/anaconda3/envs/WhatBreach/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/home/yahli/anaconda3/envs/WhatBreach/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

**Comment by KSK-IN** [comment]
Try this 
`pip install --upgrade urllib3 six
`

**Comment by rajm012** [comment]
`````
pip uninstall urllib3 requests six -y
pip install --force-reinstall "urllib3<2" "requests==2.28.2" "six==1.16.0"

``````

and 

In `WhatBreach/lib/settings.py`

# Replace line 11:
from hookers.pastebin_hook import PastebinRawHook

# With:
try:
    from hookers.pastebin_hook import PastebinRawHook

except ImportError:
    from WhatBreach.hookers.pastebin_hook import PastebinRawHook

**Comment by Nicola-Pandiscia** [comment]
After proper replacement of "urllib3" and "six" modules you have to replace the deprecated function "raw_input()" (used by the old 
Python2 interpreter) within the script "/WhatBreach/lib/formatter.py" with the function"input()" supported by Python3 interpreter.

Then the whatbreach.py script will work!
