### ISSUE TITLE
Run time error - no results but given mail is  compromised

### ISSUE THREAD

**Issue by prathikp** [Ekultek/WhatBreach#4]
```
Traceback (most recent call last):
  File "whatbreach.py", line 5, in <module>
    main()
  File "/root/WhatBreach/whatbreach/main.py", line 90, in main
    account_dumps = BeenPwnedHook(email).account_hooker()
  File "/root/WhatBreach/hookers/hibp_hook.py", line 52, in account_hooker
    HIBP_URL.format(self.email), headers=self.headers, proxies=self.proxies
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
```

**Comment by Ekultek** [comment]
@prathikp full console output please

**Comment by Ekultek** [comment]
@prathikp ping?

**Comment by Ekultek** [comment]
no response
