### ISSUE TITLE
[Tool run error] Python2 syntax in emailrep_io_hook.py

### ISSUE THREAD

**Issue by s7x** [Ekultek/WhatBreach#5]
Hi there!

There's an error in the '**hookers/emailrep_io_hook.py**' file.
The print function at line 48 is using the python2 syntax. It should use the python3 '**print()**' one.

```
Traceback (most recent call last):
  File "whatbreach.py", line 1, in <module>
    from whatbreach.main import main
  File "/usr/share/whatbreach/whatbreach/main.py", line 11, in <module>
    from hookers.emailrep_io_hook import EmailRepHook
  File "/usr/share/whatbreach/hookers/emailrep_io_hook.py", line 48
    print e
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(e)?
```

Cheers

**Comment by Ekultek** [comment]
this should be fixed, update
