### ISSUE TITLE
[Tool Exec Error] Python2 syntax in lib/formatter.py

### ISSUE THREAD

**Issue by s7x** [Ekultek/WhatBreach#6]
Hi.

There is a python2 syntax in lib/formatter.py

```
Traceback (most recent call last):
  File "whatbreach.py", line 5, in <module>
    main()
  File "/usr/share/whatbreach/whatbreach/main.py", line 44, in main
    api_tokens = grab_api_tokens()
  File "/usr/share/whatbreach/lib/settings.py", line 226, in grab_api_tokens
    "you have not provided a token for {}, enter token".format(f.split("/")[-1]), lowercase=False
  File "/usr/share/whatbreach/lib/formatter.py", line 20, in prompt
    question = raw_input(
NameError: name 'raw_input' is not defined
```
It should be **'input()'** instead of **'raw_input()'**

Cheers

**Comment by Ekultek** [comment]
Yes, whatbreach is built on python2.x and hasn’t been cross compatible to python3. Not yet anyways I’ll work on it. Thank you

**Comment by elormrescue** [comment]
Hi, i am unable to run it. This is what i get 

Traceback (most recent call last):
  File "whatbreach.py", line 1, in <module>
    from whatbreach.main import main
  File "/opt/WhatBreach/whatbreach/main.py", line 9, in <module>
    from hookers.dehashed_hook import DehashedHook
  File "/opt/WhatBreach/hookers/dehashed_hook.py", line 2, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by Ekultek** [comment]
@elormrescue what python version?

**Comment by Ekultek** [comment]
fixed via https://github.com/Ekultek/WhatBreach/commit/6c6815716b5112f4e25980b54229f037dc5e53a0

**Comment by s7x** [comment]
Hi @Ekultek the problem hasn't been fixed yet since you moved to python3.
The code is still raw_input() instead of input()
